### ISSUE TITLE
add in example output of workflow

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/harvesting-toolkit#4]

**Comment by b5** [comment]
Example added! Feel free to close if it looks up to snuff.

**Comment by dcwalk** [comment]
I'm testing the example and this is what I'm seeing
<img width="1265" alt="screen shot 2017-01-16 at 9 05 50 pm" src="https://cloud.githubusercontent.com/assets/4692834/22005259/aa725fd0-dc2f-11e6-8878-baf33a49d34e.png">

from here...
<img width="1270" alt="screen shot 2017-01-16 at 9 06 16 pm" src="https://cloud.githubusercontent.com/assets/4692834/22005260/ac84b8f4-dc2f-11e6-8dfa-460742ce9c75.png">

It appears none of the xls are saved.

For comparison, the Internet Archive Wayback version is here: https://web.archive.org/web/20161105012246/http://www.eia.gov/electricity/data/eia412/

**Comment by b5** [comment]
Example Added!
